### ISSUE TITLE
Bring Burials and Memorials content into Drupal

### ISSUE THREAD

**Issue by emilywaggoner** [emilywaggoner/va-modernization-demo#1]
- [ ] Scrape markdown files from Github and import them into Drupal
- [ ] Analyzing Analyzing existing content to determine how it maps to new structure
- [ ] Creating new paragraph type in Drupal
- [ ] Researching API script to support new structured content
